server:
  port: 8002
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: com.mzz.microservice.entities
  mapper-locations: classpath:mybatis/mapper/DeptMapper.xml

spring:
  application:
    name: microservicecloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.128.198.229:3306/cloudDB01
    username: root
    password: 123456
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 2000
eureka:
  client:
    service-url:
      #defaultZone:  http://10.128.202.134:7001/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: microservicecloud-dept8002
    prefer-ip-address: true


info:
  app.name: mzz-microservicecloud
  company.name: www.mzz.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

